# Generated by Django 3.2.9 on 2021-11-16 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='dog',
        ),
        migrations.CreateModel(
            name='Puppy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Фото')),
                ('breed', models.TextField(max_length=100, verbose_name='Порода')),
                ('color', models.TextField(max_length=255, verbose_name='Окрас')),
                ('gender', models.TextField(max_length=10, verbose_name='Пол')),
                ('age', models.CharField(max_length=2, verbose_name='Возраст')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Цена')),
                ('description', models.TextField(max_length=255, null=True, verbose_name='Описание')),
                ('parents', models.TextField(max_length=255, null=True, verbose_name='Родители')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdultDog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Фото')),
                ('breed', models.TextField(max_length=100, verbose_name='Порода')),
                ('color', models.TextField(max_length=255, verbose_name='Окрас')),
                ('gender', models.TextField(max_length=10, verbose_name='Пол')),
                ('age', models.CharField(max_length=2, verbose_name='Возраст')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Цена')),
                ('history', models.TextField(max_length=255, null=True, verbose_name='История')),
                ('habits', models.TextField(max_length=255, null=True, verbose_name='Привычки')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
