# Generated by Django 3.2.9 on 2021-11-16 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211116_0017'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Puppy',
            new_name='DogForSale',
        ),
        migrations.RenameModel(
            old_name='AdultDog',
            new_name='OurDog',
        ),
    ]
