# Generated by Django 3.2.9 on 2021-11-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20211116_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourdog',
            name='history',
            field=models.TextField(max_length=255, null=True, verbose_name='История появления'),
        ),
    ]
