# Generated by Django 3.2.9 on 2021-11-19 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_ourdog_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Фото')),
                ('breed', models.TextField(max_length=100, verbose_name='Порода')),
                ('color', models.TextField(max_length=255, verbose_name='Окрас')),
                ('gender', models.TextField(max_length=10, verbose_name='Пол')),
                ('age', models.TextField(max_length=10, verbose_name='Возраст')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
        ),
        migrations.RemoveField(
            model_name='ourdog',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='object_id',
        ),
        migrations.DeleteModel(
            name='DogForSale',
        ),
        migrations.DeleteModel(
            name='OurDog',
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='dog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.dog', verbose_name='Собака'),
            preserve_default=False,
        ),
    ]
