# Generated by Django 3.2.9 on 2021-11-19 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20211119_1503'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartProduct',
            new_name='CartDog',
        ),
    ]
