# Generated by Django 3.2.9 on 2021-11-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_rename_cartproduct_cartdog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='age',
            field=models.TextField(max_length=50, verbose_name='Возраст'),
        ),
    ]
